/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tugasbesar.view;

import com.tugasbesar.controller.DaftarProdukController;
import com.tugasbesar.database.KatalogDatabase;
import com.tugasbesar.error.DaftarProdukException;
import com.tugasbesar.event.ProdukListener;
import com.tugasbesar.model.DaftarProdukModel;
import com.tugasbesar.model.TabelDaftarProdukModel;
import com.tugasbesar.model.TabelProdukCari;
import com.tugasbesar.service.DaftarProdukDao;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Ajayfaul
 */
public class Mainmenu extends javax.swing.JFrame{

    /**
     * Creates new form Mainmenu
     */
    
    private TabelDaftarProdukModel tabelModel;
    private TabelProdukCari tabelCari;
    private DaftarProdukModel model;
    private DaftarProdukController controller;
    private TableModel model1;
    
    
    
    public Mainmenu() {
        tabelModel = new TabelDaftarProdukModel();
        tabelCari = new TabelProdukCari();
       
        
        model = new DaftarProdukModel();
      
        
        controller = new DaftarProdukController();
        controller.setModel(model);
        
        
        initComponents();
        jTable1.setModel(tabelModel);
        hasilCari.setModel(tabelCari);
        
    }

    String cariProduk;

    public JTextField getCari() {
        return cari;
    }

    public String getCariProduk() {
        return cariProduk;
    }

    public void setCariProduk(String cariProduk) {
        this.cariProduk = cariProduk;
    }

    public void setCari(JTextField cari) {
        this.cari = cari;
    }

    public JTable getHasilCari() {
        return hasilCari;
    }

    public void setHasilCari(JTable hasilCari) {
        this.hasilCari = hasilCari;
    }
    public void setTabelCari(TabelProdukCari tabelProdukCari){
        this.tabelCari = tabelCari;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnMinimizee = new javax.swing.JLabel();
        btnClosee = new javax.swing.JLabel();
        btnHome = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnListproduk = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnWishlist = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnCompare = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        listprodukPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        compareProduk = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        cari = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        hasilCari = new javax.swing.JTable();
        wishlistProduk = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        cbxProcessor = new javax.swing.JComboBox<>();
        cbxMainboard = new javax.swing.JComboBox<>();
        cbxMemory = new javax.swing.JComboBox<>();
        cbxHDD = new javax.swing.JComboBox<>();
        cbxVga = new javax.swing.JComboBox<>();
        cbxPSU = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnAddlist = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Coolvetica Rg", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Racik.");
        menuPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, -1, -1));

        btnMinimizee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tugasbesar/resource/icons8-minimize-window-32.png"))); // NOI18N
        btnMinimizee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeeMouseClicked(evt);
            }
        });
        menuPanel.add(btnMinimizee, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, -1, -1));

        btnClosee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tugasbesar/resource/icons8-cancel-32.png"))); // NOI18N
        btnClosee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseeMouseClicked(evt);
            }
        });
        menuPanel.add(btnClosee, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 0, -1, -1));

        btnHome.setBackground(new java.awt.Color(236, 240, 241));
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tugasbesar/resource/icons8-home-32 (1).png"))); // NOI18N
        jLabel3.setText("Home");

        javax.swing.GroupLayout btnHomeLayout = new javax.swing.GroupLayout(btnHome);
        btnHome.setLayout(btnHomeLayout);
        btnHomeLayout.setHorizontalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHomeLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel3)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        btnHomeLayout.setVerticalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnHomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        menuPanel.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 230, 50));

        btnListproduk.setBackground(new java.awt.Color(236, 240, 241));
        btnListproduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListprodukMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tugasbesar/resource/icons8-list-view-32 (1).png"))); // NOI18N
        jLabel4.setText("List Produk");

        javax.swing.GroupLayout btnListprodukLayout = new javax.swing.GroupLayout(btnListproduk);
        btnListproduk.setLayout(btnListprodukLayout);
        btnListprodukLayout.setHorizontalGroup(
            btnListprodukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnListprodukLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(55, 55, 55))
        );
        btnListprodukLayout.setVerticalGroup(
            btnListprodukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnListprodukLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        menuPanel.add(btnListproduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 230, 50));

        btnWishlist.setBackground(new java.awt.Color(236, 240, 241));
        btnWishlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnWishlistMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tugasbesar/resource/icons8-add-32 (1).png"))); // NOI18N
        jLabel6.setText("Wishlist");

        javax.swing.GroupLayout btnWishlistLayout = new javax.swing.GroupLayout(btnWishlist);
        btnWishlist.setLayout(btnWishlistLayout);
        btnWishlistLayout.setHorizontalGroup(
            btnWishlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnWishlistLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel6)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        btnWishlistLayout.setVerticalGroup(
            btnWishlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnWishlistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuPanel.add(btnWishlist, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 230, 50));

        btnCompare.setBackground(new java.awt.Color(236, 240, 241));
        btnCompare.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCompareMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tugasbesar/resource/search.png"))); // NOI18N
        jLabel5.setText("Search");

        javax.swing.GroupLayout btnCompareLayout = new javax.swing.GroupLayout(btnCompare);
        btnCompare.setLayout(btnCompareLayout);
        btnCompareLayout.setHorizontalGroup(
            btnCompareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCompareLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel5)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        btnCompareLayout.setVerticalGroup(
            btnCompareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCompareLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        menuPanel.add(btnCompare, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 230, 50));

        btnLogout.setBackground(new java.awt.Color(236, 240, 241));
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tugasbesar/resource/icons8-sign-out-32 (1).png"))); // NOI18N
        jLabel8.setText("Logout");

        javax.swing.GroupLayout btnLogoutLayout = new javax.swing.GroupLayout(btnLogout);
        btnLogout.setLayout(btnLogoutLayout);
        btnLogoutLayout.setHorizontalGroup(
            btnLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLogoutLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel8)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        btnLogoutLayout.setVerticalGroup(
            btnLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuPanel.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 230, 50));

        mainPanel.setLayout(new java.awt.CardLayout());

        homePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Trending Product");
        homePanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        homePanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 42, 740, 10));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tugasbesar/resource/Screenshot_31.jpg"))); // NOI18N
        homePanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tugasbesar/resource/download.jpg"))); // NOI18N
        homePanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));

        mainPanel.add(homePanel, "card2");

        listprodukPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("List Produk");
        listprodukPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 11, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        listprodukPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 42, 721, 10));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        listprodukPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 721, -1));

        mainPanel.add(listprodukPanel, "card3");

        compareProduk.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Search Product");
        compareProduk.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        compareProduk.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 42, 730, 10));

        cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cariKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cariKeyReleased(evt);
            }
        });
        compareProduk.add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 280, -1));

        jLabel14.setText("Search");
        compareProduk.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        hasilCari.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane3.setViewportView(hasilCari);

        compareProduk.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 740, 170));

        mainPanel.add(compareProduk, "card4");

        wishlistProduk.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("Wishlist");
        wishlistProduk.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 21, -1, -1));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        wishlistProduk.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 52, 737, 10));

        jLabel19.setText("Processor");
        wishlistProduk.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 80, -1, -1));

        jLabel20.setText("Mainbord");
        wishlistProduk.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 118, -1, -1));

        jLabel21.setText("Memory");
        wishlistProduk.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 156, -1, -1));

        jLabel22.setText("HDD");
        wishlistProduk.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 194, -1, -1));

        jLabel23.setText("VGA");
        wishlistProduk.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 232, -1, -1));

        jLabel24.setText("PSU");
        wishlistProduk.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 270, -1, -1));

        cbxProcessor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Intel Core i9-7980XE 2.6Ghz Up To 4.2Ghz - Cache 24.75MB  - Socket LGA 2066 Rp 28,999,000", "AMD Ryzen Threadripper 1950X 3.4Ghz Up To 4.0Ghz Cache 32MB 180W TR4 Rp 14,399,000", " " }));
        wishlistProduk.add(cbxProcessor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 560, -1));

        cbxMainboard.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asus ROG Zenith Extreme (TR4 ,AMD Promontory X399, DDR4, USB3.1, SATA3)  Rp 8,544,000", "ASRock Fatal1ty X399 Professional Gaming (TR4 ,AMD Promontory X399, DDR4, USB3.1, SATA3) Rp 7,299,000", " ", " " }));
        wishlistProduk.add(cbxMainboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 118, 560, -1));

        cbxMemory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apacer SO-DIMM DDR4 PC19200 2400Mhz 8GB Rp 740.000 ", "OCPC BLADE DDR4 PC19200 2400Mhz 4GB (1x4GB) Rp 570,000", " " }));
        wishlistProduk.add(cbxMemory, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 156, 560, -1));

        cbxHDD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seagate Backup Plus Desktop 3TB 1,049,000", "Toshiba 500GB SATA3 7200RPM Rp 570,000", " " }));
        wishlistProduk.add(cbxHDD, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 194, 560, -1));

        cbxVga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XFX Radeon RX VEGA 64 8GB HBM2 Rp 9,750,000 ", "Inno 3D Geforce GTX 1080 Ti 11GB DDR5X Rp 10,250,000", " " }));
        wishlistProduk.add(cbxVga, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 232, 560, -1));

        cbxPSU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Super Flower Silver Green 600W PSU - SF-600R14SE - 80 PLUS SILVER Rp 450,000", "GAMEMAX PSU 650W GP-650 - 80+ Bronze Certified Rp 680,000", " " }));
        wishlistProduk.add(cbxPSU, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 560, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        wishlistProduk.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 760, 220));

        btnAddlist.setBackground(new java.awt.Color(51, 51, 51));
        btnAddlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddlistMouseClicked(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tugasbesar/resource/icons8-plus-math-32.png"))); // NOI18N
        jLabel25.setText("Add");

        javax.swing.GroupLayout btnAddlistLayout = new javax.swing.GroupLayout(btnAddlist);
        btnAddlist.setLayout(btnAddlistLayout);
        btnAddlistLayout.setHorizontalGroup(
            btnAddlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAddlistLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel25)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        btnAddlistLayout.setVerticalGroup(
            btnAddlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        wishlistProduk.add(btnAddlist, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, -1, 40));

        mainPanel.add(wishlistProduk, "card5");

        menuPanel.add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 790, 540));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tugasbesar/resource/Moss (1).jpg"))); // NOI18N
        menuPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCloseeMouseClicked

    private void btnMinimizeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeeMouseClicked
        // TODO add your handling code here:
        setState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizeeMouseClicked

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(homePanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnListprodukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListprodukMouseClicked
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(listprodukPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        try {
          loadDatabase();
         } catch (SQLException | DaftarProdukException ex) {
             Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        
    }//GEN-LAST:event_btnListprodukMouseClicked

    private void btnCompareMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCompareMouseClicked
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(compareProduk);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnCompareMouseClicked

    private void btnWishlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWishlistMouseClicked
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(wishlistProduk);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnWishlistMouseClicked

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
        int dialogButton = JOptionPane.YES_NO_OPTION;
        JOptionPane.showConfirmDialog(null, "Are you sure you want Logout and Exit?", "WARNING", dialogButton);
        if (dialogButton == JOptionPane.YES_OPTION) {
            System.exit(0);
        if (dialogButton == JOptionPane.NO_OPTION) {
                remove(dialogButton);
            }
        }
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnAddlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddlistMouseClicked
        // TODO add your handling code here:
        int processor =0;
        int mainboard = 0;
        int hdd = 0;
        int memory =0;
        int psu =0;
        int vga =0;
        int totalharga;
        
        //
        if (cbxProcessor.getSelectedItem()=="Intel Core i9-7980XE 2.6Ghz Up To 4.2Ghz - Cache 24.75MB  - Socket LGA 2066 Rp 28,999,000") {
                processor=28999000;
            }
        else if (cbxProcessor.getSelectedItem()=="AMD Ryzen Threadripper 1950X 3.4Ghz Up To 4.0Ghz Cache 32MB 180W TR4 Rp 14,399,000"){
            processor=14399000;
        }
        //
        if (cbxMainboard.getSelectedItem()=="Asus ROG Zenith Extreme (TR4 ,AMD Promontory X399, DDR4, USB3.1, SATA3)  Rp 8,544,000"){
            mainboard=8544000;
        }else if(cbxMainboard.getSelectedItem()=="ASRock Fatal1ty X399 Professional Gaming (TR4 ,AMD Promontory X399, DDR4, USB3.1, SATA3) Rp 7,299,000"){
            mainboard=7299000;
        }
        //
        if (cbxHDD.getSelectedItem()=="Seagate Backup Plus Desktop 3TB 1,049,000"){
            hdd=1049000;
        }else if(cbxHDD.getSelectedItem()=="Toshiba 500GB SATA3 7200RPM Rp 570,000"){
            hdd=570000;
        }
        //
        if (cbxMemory.getSelectedItem()=="Apacer SO-DIMM DDR4 PC19200 2400Mhz 8GB Rp 740.000 "){
            memory=740000;
        }else if(cbxMemory.getSelectedItem()=="OCPC BLADE DDR4 PC19200 2400Mhz 4GB (1x4GB) Rp 570,000"){
            memory=570000;
        }
        //
        if (cbxVga.getSelectedItem()=="XFX Radeon RX VEGA 64 8GB HBM2 Rp 9,750,000"){
            vga=9750000;
        }else if(cbxVga.getSelectedItem()=="Inno 3D Geforce GTX 1080 Ti 11GB DDR5X Rp 10,250,000"){
            vga=10250000;
        }
        //
        if (cbxPSU.getSelectedItem()=="Super Flower Silver Green 600W PSU - SF-600R14SE - 80 PLUS SILVER Rp 450,000"){
            psu=450000;
        }else if(cbxPSU.getSelectedItem()=="GAMEMAX PSU 650W GP-650 - 80+ Bronze Certified Rp 680,000"){
            psu=680000;
        }
        
        totalharga=hdd+mainboard+memory+processor+psu+vga;
        
        jTextArea1.setText("Processor :"+ cbxProcessor.getSelectedItem() +"\n"
                            + "Mainboard" + cbxMainboard.getSelectedItem() +"\n"
                            + "Memory"+ cbxMemory.getSelectedItem() +"\n"
                            + "HDD"+ cbxHDD.getSelectedItem() +"\n"
                            + "VGA"+ cbxVga.getSelectedItem() +"\n"
                            + "PSU"+ cbxPSU.getSelectedItem() +"\n"
                            + "TOTAL HARGA Rp." + totalharga 
        );
    }//GEN-LAST:event_btnAddlistMouseClicked

    private void cariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariKeyPressed

    private void cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariKeyReleased
        // TODO add your handling code here:
        hasilCari.setModel(tabelCari);
        cariProduk = cari.getText();
        try {
            DaftarProdukDao dao = KatalogDatabase.getDaftarProdukDao();
            tabelCari.setList(dao.selectCariProduk(cariProduk));
            hasilCari.setModel(tabelCari);
        } catch (SQLException ex) {
            Logger.getLogger(Mainmenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DaftarProdukException ex){
            Logger.getLogger(Mainmenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        hasilCari.setModel(tabelCari);
       
    }//GEN-LAST:event_cariKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAddlist;
    private javax.swing.JLabel btnClosee;
    private javax.swing.JPanel btnCompare;
    private javax.swing.JPanel btnHome;
    private javax.swing.JPanel btnListproduk;
    private javax.swing.JPanel btnLogout;
    private javax.swing.JLabel btnMinimizee;
    private javax.swing.JPanel btnWishlist;
    private javax.swing.JTextField cari;
    private javax.swing.JComboBox<String> cbxHDD;
    private javax.swing.JComboBox<String> cbxMainboard;
    private javax.swing.JComboBox<String> cbxMemory;
    private javax.swing.JComboBox<String> cbxPSU;
    private javax.swing.JComboBox<String> cbxProcessor;
    private javax.swing.JComboBox<String> cbxVga;
    private javax.swing.JPanel compareProduk;
    private javax.swing.JTable hasilCari;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel listprodukPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel wishlistProduk;
    // End of variables declaration//GEN-END:variables
    public void loadDatabase() throws SQLException, DaftarProdukException{
        DaftarProdukDao dao = KatalogDatabase.getDaftarProdukDao();
        tabelModel.setList(dao.selectAllDaftarProduk());
    }

    private void onChange(DaftarProdukModel model) {
      
    }

}
