/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tugasbesar.view;

import com.tugasbesar.controller.DaftarProdukController;
import com.tugasbesar.database.KatalogDatabase;
import com.tugasbesar.error.DaftarProdukException;
import com.tugasbesar.model.DaftarProdukModel;
import com.tugasbesar.model.TabelDaftarProdukModel;
import com.tugasbesar.service.DaftarProdukDao;
import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author rezaa
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    private TabelDaftarProdukModel tabelModel;
    private DaftarProdukModel model;
    private DaftarProdukController controller;
    private TableModel model1;
    public Register() {
        tabelModel = new TabelDaftarProdukModel();
        
        model = new DaftarProdukModel();
        
        controller = new DaftarProdukController();
        controller.setModel(model);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRegister = new javax.swing.JPanel();
        btnSignup = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        btnLoginhere = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        btnClose = new javax.swing.JLabel();
        btnMinimize = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRegister.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSignup.setBackground(new java.awt.Color(255, 255, 255));
        btnSignup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSignupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSignupMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSignupMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSignupMouseReleased(evt);
            }
        });

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel37.setText("Sign Up");

        javax.swing.GroupLayout btnSignupLayout = new javax.swing.GroupLayout(btnSignup);
        btnSignup.setLayout(btnSignupLayout);
        btnSignupLayout.setHorizontalGroup(
            btnSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSignupLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        btnSignupLayout.setVerticalGroup(
            btnSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSignupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRegister.add(btnSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 280, 40));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Username");
        panelRegister.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, -1));

        jLabel39.setFont(new java.awt.Font("Coolvetica Rg", 1, 48)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Racik.");
        panelRegister.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 230, -1));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Login & Sign Up. ");
        panelRegister.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Enter Your Details Here.");
        panelRegister.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, -1));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Name");
        panelRegister.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Email");
        panelRegister.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, -1, -1));

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Password");
        panelRegister.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, -1, -1));

        txtNama.setBackground(new java.awt.Color(52, 113, 106));
        txtNama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNama.setForeground(new java.awt.Color(255, 255, 255));
        txtNama.setBorder(null);
        panelRegister.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 280, 30));

        txtUsername.setBackground(new java.awt.Color(52, 113, 106));
        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(255, 255, 255));
        txtUsername.setBorder(null);
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        panelRegister.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 280, 30));

        txtEmail.setBackground(new java.awt.Color(52, 113, 106));
        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setBorder(null);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        panelRegister.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 280, 30));

        txtPassword.setBackground(new java.awt.Color(52, 113, 106));
        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setBorder(null);
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        panelRegister.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 280, 30));
        panelRegister.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 280, 10));
        panelRegister.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 280, 10));
        panelRegister.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 280, 10));
        panelRegister.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 280, 10));

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tugasbesar/resource/icons8-heart-outline-32.png"))); // NOI18N
        panelRegister.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 492, 30, 30));

        jLabel46.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("in Indonesia");
        panelRegister.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, -1, -1));

        jLabel47.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Build with ");
        panelRegister.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, -1));

        btnLoginhere.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLoginhere.setForeground(new java.awt.Color(255, 255, 255));
        btnLoginhere.setText("Login Here.");
        btnLoginhere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginhereMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginhereMouseEntered(evt);
            }
        });
        panelRegister.add(btnLoginhere, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, -1, -1));

        jLabel48.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Already have an account ?");
        panelRegister.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 490, -1, -1));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tugasbesar/resource/icons8-cancel-32.png"))); // NOI18N
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });
        panelRegister.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 30, 30));

        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tugasbesar/resource/icons8-minimize-window-32.png"))); // NOI18N
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
        });
        panelRegister.add(btnMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 30, 30));

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tugasbesar/resource/Moss (1).jpg"))); // NOI18N
        panelRegister.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 550));

        getContentPane().add(panelRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignupMouseClicked
        // TODO add your handling code here:
       
        
        String nama = txtNama.getText();
        String usname = txtUsername.getText();
        String passw = txtPassword.getText();
        String email = txtPassword.getText();
        if(nama.isEmpty()||usname.isEmpty()||passw.isEmpty()||email.isEmpty()){
            JOptionPane.showMessageDialog(null, "Registrasi gagal, pastikan seluruh inputan terisi");
        }
        else{
            JOptionPane.showMessageDialog(null,"Anda berhasil membuat akun \n");
            txtNama.setText("");
            txtUsername.setText("");
            txtPassword.setText("");
            txtEmail.setText("");
            this.setVisible(false);
            new Mainmenu().setVisible(true);
        }
    }//GEN-LAST:event_btnSignupMouseClicked

    private void btnSignupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignupMouseEntered
        // TODO add your handling code here:
        btnSignup.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_btnSignupMouseEntered

    private void btnSignupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignupMouseExited
        // TODO add your handling code here:
        btnSignup.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnSignupMouseExited

    private void btnSignupMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignupMousePressed
        // TODO add your handling code here:
        btnSignup.setBackground(new Color(179,179,179));
    }//GEN-LAST:event_btnSignupMousePressed

    private void btnSignupMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignupMouseReleased
        // TODO add your handling code here:
        btnSignup.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnSignupMouseReleased

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnLoginhereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginhereMouseClicked
        // TODO add your handling code here:
        //remove
        dispose();
        Login ln = new Login();
        ln.setVisible(true);
        

    }//GEN-LAST:event_btnLoginhereMouseClicked

    private void btnLoginhereMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginhereMouseEntered
        // TODO add your handling code here:
        btnLoginhere.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_btnLoginhereMouseEntered

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        // TODO add your handling code here:
        setState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClose;
    private javax.swing.JLabel btnLoginhere;
    private javax.swing.JLabel btnMinimize;
    private javax.swing.JPanel btnSignup;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JPanel panelRegister;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNama;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
    public void loadDatabase() throws SQLException, DaftarProdukException{
        DaftarProdukDao dao = KatalogDatabase.getDaftarProdukDao();
        tabelModel.setList(dao.selectAllDaftarProduk());
    }
}
